name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create resource group rg-copilot-nodejs-todo
      - name: Create resource group
        run: az group create --name rg-copilot-nodejs-todo --location eastus

      # Create cosmosdb with default api
      - name: Create cosmosdb
        run: az cosmosdb create --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --locations regionName="East US" failoverPriority=0 isZoneRedundant=False

      # Create database todos with collection tasks
      - name: Create database and collection
        run: |
          az cosmosdb sql database create --account-name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --name todos
          az cosmosdb sql container create --account-name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --database-name todos --name tasks --partition-key-path /id --throughput 400

      # Deploy webapp using node 20
      - name: Deploy webapp
        run: az webapp up --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --runtime "node|20-lts"

      # Retrieve cosmos endpoint and key
      - name: Retrieve cosmos credentials
        run: |
          echo "COSMOS_ENDPOINT=$(az cosmosdb show --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --query documentEndpoint --output tsv)" >> $GITHUB_ENV
          echo "COSMOS_KEY=$(az cosmosdb keys list --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --query primaryMasterKey --output tsv)" >> $GITHUB_ENV

      # Set cosmos variables in web app
      - name: Set cosmos variables
        run: |
          az webapp config appsettings set --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --settings COSMOS_ENDPOINT=${{ env.COSMOS_ENDPOINT }} COSMOS_KEY=${{ env.COSMOS_KEY }}
